<?php

declare(strict_types=1);

/**
 * @file
 * Provides a si mapping entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function si_mapping_theme(): array {
  return [
    'si_mapping' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for si mapping templates.
 *
 * Default template: si-mapping.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the si mapping information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_si_mapping(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function si_mapping_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish si mappings.
      $storage = \Drupal::entityTypeManager()->getStorage('si_mapping');
      $si_mapping_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($si_mapping_ids) as $si_mapping) {
        $si_mapping->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize si mappings.
      $storage = \Drupal::entityTypeManager()->getStorage('si_mapping');
      $si_mapping_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($si_mapping_ids) as $si_mapping) {
        $si_mapping->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function si_mapping_user_predelete(UserInterface $account): void {
  // Delete si mappings that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('si_mapping');
  $si_mapping_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($si_mapping_ids)
  );
}

use Drupal\Core\Form\FormStateInterface;

function _si_mapping_is_si_mapping_view($view, &$options = []): bool {
  if(
    !!($extenders = $view->getDisplay()->getExtenders())
    && (array_key_exists('si_mapping_view', $extenders))
    && !empty($extenders['si_mapping_view']->options['template'])
  ) {
    $options = $extenders['si_mapping_view']->options;
    return TRUE;
  }

  return False;
}

/**
 * Implements hook_form_alter().
 *
 * This catches all forms; then we check for the Views display edit form.
 */
function si_mapping_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'views_exposed_form') !== FALSE) {
    $view = $form_state->get('view');

    if (isset($view->filter['bundle'])) {
      $table = $view->filter['bundle']->table;
      if (strpos($table, 'si_mapping') !== FALSE) {
        if(_si_mapping_is_si_mapping_view($view, $options)
        && !empty($options['template'])) {
          $form['#attached']['library'][] = 'si_mapping/si_mapping';
          $form['si_mapping'] = [
            'template' => $options['template'],
          ];
        }
      }
    }
  }
}

