si_mapping.si_mapping_type.*:
  type: config_entity
  label: 'Si mapping type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

si_mapping.si_mapping_si_mapping_item_type.*:
  type: config_entity
  label: 'SI Mapping Item type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
