<?php

/**
 * @file
 * Installation hooks for the Schema.org Blueprints Diagram.
 */

declare(strict_types=1);

/**
 * Issue #3437127: Display diagrams as node task.
 */
function schemadotorg_diagram_update_10000(): void {
  \Drupal::configFactory()
    ->getEditable('schemadotorg_diagram.settings')
    ->set('node_task', FALSE)
    ->save();
}

/**
 * Issue #3605775: Make the maximum diagram depth configurable.
 */
function schemadotorg_diagram_update_10001(): void {
  \Drupal::configFactory()
    ->getEditable('schemadotorg_diagram.settings')
    ->set('max_depth', 3)
    ->save();
}
