<?php

use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function leaflet_full_page_theme($existing, $type, $theme, $path) {
  $module_path = \Drupal::service('extension.list.module')->getPath('leaflet_full_page');
  return [
    'views_view__leaflet_full_page__legend' => [
      'template' => 'views-view--leaflet-full-page--legend', // Filename without .html.twig
      'path' => $module_path . '/templates',
    ],
    'views_view__leaflet_full_page__no_legend' => [
      'template' => 'views-view--leaflet-full-page--no-legend', // Filename without .html.twig
      'path' => $module_path . '/templates',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function leaflet_full_page_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $leaflet_full_page_extenders = $view->display_handler->getOption('display_extenders')['leaflet_full_page_display_extender'] ?? [];

  if (isset($leaflet_full_page_extenders['template'])) {
    $suggestions[] = 'views_view__leaflet_full_page__' . $leaflet_full_page_extenders['template'];
  } else {

  }
}



function _leaflet_full_page_is_si_mapping_view($view, &$options = []): bool {
  if(
    !!($extenders = $view->getDisplay()->getExtenders())
    && (array_key_exists('leaflet_full_page_view', $extenders))
    && !empty($extenders['leaflet_full_page_view']->options['template'])
  ) {
    $options = $extenders['leaflet_full_page_view']->options;
    return TRUE;
  }

  return False;
}

/**
 * Implements hook_form_alter().
 *
 * This catches all forms; then we check for the Views display edit form.
 */
function leaflet_full_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'views_exposed_form') !== FALSE) {
    $view = $form_state->get('view');

    if (isset($view->filter['bundle'])) {
      $table = $view->filter['bundle']->table;
      if (strpos($table, 'leaflet_full_page') !== FALSE) {
        if(_leaflet_full_page_is_si_mapping_view($view, $options)
          && !empty($options['template'])) {
          $form['leaflet_full_page'] = [
            'template' => $options['template'],
          ];
        }
      }
    }
  }
}

function leaflet_full_page_views_pre_render(ViewExecutable $view): void {
  if (strpos($view->id(), 'leaflet_full_page') !== FALSE) {
    if (strpos($view->current_display, 'items') === FALSE) {
      $view->element['#attached']['drupalSettings']['leaflet_full_page']['currentDisplay'] = $view->current_display;
    }
  }
}
