<?php

/**
 * @file
 * Provides flag integration for language fields and switchers.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\flags_language\Hook\FlagsLanguageHooks;
use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_language_switch_links_alter().
 *
 * Implemented to add flags to the language switcher links.
 */
#[LegacyHook]
function flags_language_language_switch_links_alter(array &$links, $type, $path) {
  \Drupal::service(FlagsLanguageHooks::class)->languageSwitchLinksAlter($links, $type, $path);
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 *
 * Implemented to attach flags CSS to the language switcher block.
 */
#[LegacyHook]
function flags_language_block_view_language_block_alter(
  array &$build,
  BlockPluginInterface $block,
) {
  \Drupal::service(FlagsLanguageHooks::class)->blockViewLanguageBlockAlter($build, $block);
}

/**
 * Implements hook_field_widget_info_alter().
 */
function flags_language_field_widget_info_alter(array &$info) {
  // Allow to use widget language_select_menu only when select_icons enabled.
  if (\Drupal::moduleHandler()->moduleExists('select_icons')) {
    $info['language_select_menu']['field_types'][] = 'language';
  }
}
