<?php

/**
 * @file
 * Provides country and territory flags for Drupal.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\flags\Hook\FlagsHooks;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function flags_theme($existing, $type, $theme, $path) {
  return \Drupal::service(FlagsHooks::class)->theme($existing, $type, $theme, $path);
}

/**
 * Implements hook_preprocess_HOOK() for flags.
 */
function flags_preprocess_flags(array &$variables) {
  $flag = $variables['code'];
  // Use mapping service to allow others to provide their own mappings.
  // Try to invoke source specific service if it exists.
  $serviceName = 'flags.mapping.' . $variables['source'];
  if (\Drupal::hasService($serviceName)) {
    $flag = \Drupal::service($serviceName)->map($flag);
    $extra = \Drupal::service($serviceName)->getExtraClasses();
  }
  else {
    throw new \InvalidArgumentException(sprintf('Service %s to map source "%s" is not defined.', $serviceName, $variables['source']));
  }

  $variables['flag'] = $flag;

  if (empty($variables['attributes'])) {
    $variables['attributes'] = new Attribute();
  }

  if (empty($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }

  $variables['attributes']['class'][] = 'flag';
  $variables['attributes']['class'][] = 'flag-' . $flag;

  if (!empty($extra)) {
    $variables['attributes']->addClass($extra);
  }

  unset($variables['source']);
}
